spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      platform: postgres
      mode: always
      separator: "^^^ END OF SCRIPT ^^^"

logging:
  level:
    org:
      springframework:
        security: debug

    web: debug